# -*- coding: utf-8 -*-
"""TfIdf-Model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lMtcp7eRm0cfS97teOz9OCE5YRAJWGTQ
"""

import pandas as pd
import joblib
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder

from sklearn.svm import LinearSVC
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, classification_report
import seaborn as sns

train_df = pd.read_csv("./news_headlines.csv")
train_df

sns.countplot(y="tags", data=train_df, palette="pastel")

le = LabelEncoder()
Y = le.fit_transform(train_df['tags'])

X_train, X_test, y_train, y_test = train_test_split(train_df['post'], Y, test_size=0.2, random_state=5)

pipeline = Pipeline([
    ('vectorizer', TfidfVectorizer()),
    ('clf', LinearSVC())
])
pipeline.steps

pipeline.fit(X_train,y_train)

pred = pipeline.predict(X_test)

pred

y_test

accuracy_score(y_test, pred)

print(classification_report(y_test, pred))

le.classes_

text = "Bolsonaro virou ministro no Brasil"

prediction = pipeline.predict([text])
le.classes_[prediction]

le.inverse_transform(prediction)[0]

joblib.dump(pipeline, "model.joblib")